travis:
  secure:
    BINSTAR_TOKEN: Lo4zAyS6xskMTGaRhlyQe1aTFrFaFnuiq+8BtHNSTH9GTUh5P3t1GXbAn7DF+n6JIUnhWzjTnfXb7/xXvCL/iGZkABYDQzW0MoeDIPZORz2cPJ3v8WXfckByVDA1/x/iCH0fwdaj6SsjqpgfWdLRya12ihEMVaUdXEMp5niQMys8kIVfGae2NVEVGqBkLqZMYIExwa2j0FWzKL/fliRPBHx+2QNljJaglQc1oWkBsy84oEXnPGbF78ppwIjZGs/2DqMdMRFRSQ6yLmgtXO2qcFlqvnw8mjTEI+gQ/7hSvaRhx8ME/datfn8O+Dg/VeVuVuBHkWiKo9jULGcJ41gJ2JPifjLd4aXDJDLGYA5UyIUk+WMvWj+i5uqemPWDT017J575Qudu7/T0Jn/GPvM6gwyR4Ek90/QVPK/MMZlscXX7AeK0LEw2zjRNsOJ9GMGwv8DbB3M+HOkIJO8oz2PQXGlYXmkHpzVMQ3CTrLUDc7YRaFDbVU11okCIE9aR0hwfDvUht9CmTk/iJ5orGwcR7wLabTa8X/vVP+OcTXH+ufcG0BBVa3zZp2tq8C00Ju4F6/g9ZZvmpEiSzRqAiYTShFpBgOIrnTzZE+s/jvcgnz47pcru/qIkmSz6CWUOYqmnKNdQSKfxUmvVZnVMwBRoVUa3aexayknbNfW3i2SFeiU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
