travis:
  secure:
    BINSTAR_TOKEN: FxAW82/jpiZNcCMv5oTqfNw8hEZ/TmQSl8L3UCoBJg/8dHQa2d802ua58nYxKp0d/vleUSQr7kxh80vqJlO3fQFcLH52ivWrscg3yqKRi/YEU3gsYadLbmuO77Lk650dAXJ+IHNmSla1ZBD9sY/yP6qDuNzM+SVxDexu5yDj9mhGfmPkLosEL1TUz4z/KY1aF5KC9OO+p+h6rfh2I5S1PXQLftyGSDgs6DvLRF/OVdNe/5yS7q7echuwOWoDC2RN9Zkl8mTGZRkhRjb3+a7Vc6fX1L9BhgjY+3+R7YvBY96rcsrugMq2j3VDX+wtWZ23Ul7jRUxoMOI44vmvYR1US76NdMu031BaapQEGz9Rjh30837M4MfN7VMJPqkXsgppkMXrBx4g2OfEeYBsnjg9+rmvj8OAxS2yBznNAQso94wzU7sbpBZDDA+HK2mFlTLfEPG/PesNUOwIW9tUV70hx2eWqy4UDPkOax2+8tyVwy03i2BcNOh0bufZY62oJf0NYvXqUyC7fvcnCmnr7Ol7YnmKSlKeFJ1INNuCLzRIKDXq3l6GU/lHHLsIDfnmfIokMHxwEKikhXFGbp6gTnr5ZYdsUSiDdWuWum+fGzlAvMWzc7smslXTAiP9E7bkqi0XK0+foWzKPUiXOR4+zrWzBxVpwJ1YzSG6YbTvi8LIAsU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
