travis:
  secure:
    BINSTAR_TOKEN: bpyY9cgOGHNjNACMp4fqa3ekpwr7Br1lCJWM5qnn7+Gl4R5Ru2LtLGYohLPJF/Eluma6EFnrtm3pV4JuAAtMxKuLwjiDMWUk8VawaAjYGi7SxSMQJfebB3X5eExJ9JsttH+yg9V9BNRfDMRsiF0LxofrskIwq8mXlRfCmEz932w7wiZq7EmMMDa37oZMnZxAQOAUsdmbLisGaEWYlesb9oJGBQnGMO8t+zAdMd3SUUDDSmR+FM3yp/9mfIKWsUH2UwooFsacGhryldDO3Annmrq2L++HJwOv07+cPrv3/kcjC0XAO7ehgD1buApaPgjAPiyKNBf39lsbMgDLs9Wi821zYVTgXH0eInYWzT020j8zEQtsY5qtWaoHmud02tFpHAia81DzE6sAFq8ls29oYNMZ/fH+5PkENE732Z9Js/dw36CEaoSpxCqcQrsIjLDkWbii3bnA8e64TsFBFSauWKCjYerCmO8I/DFLTkQKYeIe/PupzHtYqYHTbWHIP7TEY6Up8De07vFear764biiId5+pbEaxZ1EHVU72KuSOxs2D85ygtVza3uWdsz/bZkwzORAf7mDsz2Qy3To4pABOaFRgGjXqADaLe3g8gTAUP2awgh+Sh27M85xAY5Dp6Dkjuz/qdaXdN4mK66ehpaYg1czB8iOmNUkho0xiHBNsu4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
